import { budget2025 } from '../data/2025.js';
import { campaign, policyProfiles } from '../data/campaign-2025-2030.js';
import { projectionRule, childProjectionRule } from '../data/projection-rules.js';

const round=n=>Math.round(n*1e6)/1e6;
const expenseParents=budget2025.expenses,revenueParents=budget2025.revenues;
export const itemDefinitions=[...expenseParents,...revenueParents,...expenseParents.flatMap(x=>x.children||[])];
export const initialAmounts=()=>Object.fromEntries(itemDefinitions.map(x=>[x.id,x.value]));
export function policyEffect(instance,year){if(year<instance.adoptedYear||instance.cancelledYear&&year>=instance.cancelledYear)return {revenue:0,expense:0};const profile=policyProfiles[instance.policyId];if(!profile)return {revenue:0,expense:0};const age=year-instance.adoptedYear;if(profile.duration&&age>=profile.duration)return {revenue:0,expense:0};const baseRevenue=profile.revenueByYear?.[year]??(Array.isArray(profile.revenue)?(profile.revenue[age]||0):(profile.revenue||0)),baseExpense=profile.expenseByYear?.[year]??(Array.isArray(profile.expense)?(profile.expense[age]||0):(profile.expense||0));let factor=1;for(let y=instance.adoptedYear+1;y<=year;y++){const a=campaign.assumptions[y];factor*=profile.index==='wages'?1+a.wageGrowth:profile.index==='inflation'?1+a.inflation:profile.index==='nominalGdp'?1+a.nominalGdpGrowth:1;}return {revenue:round(baseRevenue*factor),expense:round(baseExpense*factor)};}
export function policyTotals(game,year){return game.policies.reduce((s,p)=>{const e=policyEffect(p,year);return {revenue:s.revenue+e.revenue,expense:s.expense+e.expense};},{revenue:0,expense:0});}
function fiscalNodeValue(ys,parent){return ys.amounts[parent.id]??ys.baselineAmounts[parent.id]??parent.value;}
export function nodeDelta(ys,type){const parents=type==='expense'?expenseParents:revenueParents;return parents.reduce((s,p)=>s+fiscalNodeValue(ys,p)-(ys.baselineAmounts[p.id]??p.value),0);}
export function calculateYear(game,year=game.viewYear){const ys=game.years[year],pol=policyTotals(game,year);if(ys.status==='closed'&&ys.closing)return ys.closing;const revenue=ys.baseRevenue+nodeDelta(ys,'revenue')+pol.revenue,expenditure=ys.baseExpense+nodeDelta(ys,'expense')+pol.expense,balance=revenue-expenditure,closingDebt=Math.max(0,ys.openingDebt-balance),debtService=fiscalNodeValue(ys,expenseParents.find(x=>x.id==='debtservice'));return {revenue:round(revenue),expenditure:round(expenditure),balance:round(balance),openingDebt:ys.openingDebt,closingDebt:round(closingDebt),debtService:round(debtService),gdp:ys.assumptions.gdp,debtToGdp:round(closingDebt/ys.assumptions.gdp*100),policyRevenue:round(pol.revenue),policyExpense:round(pol.expense)};}
export function newGame(){const amounts=initialAmounts(),a=campaign.assumptions[2025];return {schemaVersion:5,campaign,currentYear:2025,viewYear:2025,phase:'planning',policies:[],years:{2025:{year:2025,status:'planning',baseRevenue:budget2025.approved.revenue,baseExpense:budget2025.approved.expense,baseDebtService:budget2025.assumptions.approvedDebtService,openingDebt:budget2025.assumptions.openingDebt,baselineAmounts:{...amounts},amounts:{...amounts},assumptions:a,decisions:[]}},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};}
function projectedDebtService(closing,a){const debtChange=closing.closingDebt-closing.openingDebt,oldRate=closing.openingDebt>0?closing.debtService/closing.openingDebt:0,newDebtCost=Math.max(0,debtChange)*a.marginalInterestRate,refinancingEffect=closing.openingDebt*a.refinancingShare*(a.marginalInterestRate-oldRate);return round(Math.max(0,closing.debtService+newDebtCost+refinancingEffect));}
export function projectNextYear(ys,closing,nextYear){const a=campaign.assumptions[nextYear],nextDebtService=projectedDebtService(closing,a),baselineAmounts={},preliminary={};for(const p of revenueParents)baselineAmounts[p.id]=round(fiscalNodeValue(ys,p)*projectionRule(p.id,'revenue',a).factor);for(const p of expenseParents){if(p.id==='debtservice')continue;preliminary[p.id]=fiscalNodeValue(ys,p)*projectionRule(p.id,'expense',a).factor;}const currentStructuralExpense=expenseParents.reduce((s,p)=>s+fiscalNodeValue(ys,p),0),targetExpense=currentStructuralExpense*(1+a.targetExpenseGrowth),preliminaryNonDebt=Object.values(preliminary).reduce((s,v)=>s+v,0),calibration=preliminaryNonDebt>0?Math.max(0,targetExpense-nextDebtService)/preliminaryNonDebt:1;for(const p of expenseParents){if(p.id==='debtservice'){baselineAmounts[p.id]=nextDebtService;continue;}baselineAmounts[p.id]=round(preliminary[p.id]*calibration);const children=p.children||[];if(children.length){const projectedChildren=children.map(c=>({c,value:(ys.amounts[c.id]??ys.baselineAmounts[c.id]??c.value)*childProjectionRule(c.id,p.id,a).factor})),childrenTotal=projectedChildren.reduce((s,x)=>s+x.value,0),childrenScale=childrenTotal>0?baselineAmounts[p.id]/childrenTotal:0;projectedChildren.forEach(({c,value})=>baselineAmounts[c.id]=round(value*childrenScale));}}return {baselineAmounts,baseRevenue:round(revenueParents.reduce((s,p)=>s+baselineAmounts[p.id],0)),baseExpense:round(expenseParents.reduce((s,p)=>s+baselineAmounts[p.id],0)),baseDebtService:nextDebtService};}
export function closeCurrentYear(game){const year=game.currentYear,ys=game.years[year],closing=calculateYear(game,year);closing.year=year;ys.closing=closing;ys.status='closed';ys.closedAt=new Date().toISOString();if(year>=campaign.endYear){game.phase='game_result';game.viewYear=year;return game;}const next=year+1,projection=projectNextYear(ys,closing,next);game.years[next]={year:next,status:'planning',...projection,openingDebt:closing.closingDebt,amounts:{...projection.baselineAmounts},assumptions:campaign.assumptions[next],decisions:[]};game.currentYear=next;game.viewYear=next;game.phase='planning';game.updatedAt=new Date().toISOString();return game;}
export function campaignSummary(game){const closed=Object.values(game.years).filter(y=>y.status==='closed'),snapshots=closed.map(y=>y.closing),first=snapshots[0],last=snapshots.at(-1),cumulativeBalance=snapshots.reduce((s,x)=>s+x.balance,0),interest=snapshots.reduce((s,x)=>s+x.debtService,0),social=game.policies.filter(p=>/pension|lunch|teacher|non-teaching/.test(p.policyId)).length,investment=game.policies.filter(p=>/motorway|hospital|dukovany/.test(p.policyId)).length,taxes=game.policies.filter(p=>/tax|vat|super-gross/.test(p.policyId)).length,profile=investment>=3?'Investiční expanze':social>=3?'Sociálně orientovaný správce':cumulativeBalance>-900?'Fiskální konsolidátor':'Rozpočtový expanzionista';return {closed:closed.length,cumulativeBalance:round(cumulativeBalance),interest:round(interest),debtChange:first&&last?round(last.closingDebt-first.openingDebt):0,debtToGdp:last?.debtToGdp||0,profile,axes:{sustainability:Math.max(0,100-(last?.debtToGdp||50)),stability:Math.max(20,90-game.policies.length*3),investment:20+investment*22,social:20+social*18,taxBurden:20+taxes*25,resilience:Math.max(15,100-(last?.debtToGdp||50))}};}
